export interface ExperienceData {
  id: string;
  name: { en: string; es: string };
  dest: "nayarit" | "maya";
  destLabel: string;
  duration: { en: string; es: string };
  type: "water" | "adventure" | "culture" | "private" | "family";
  desc: { en: string; es: string };
  img: string;
  alt: string;
}

export const ALL_EXPERIENCES: ExperienceData[] = [
  { id: "biolum", name: { en: "Bioluminescence night paddle", es: "Paddle nocturno bioluminiscente" }, dest: "nayarit", destLabel: "Riviera Nayarit", duration: { en: "2.5 hrs", es: "2.5 h" }, type: "water", desc: { en: "Glide across glowing waters after dark on a guided night paddle through a protected bay.", es: "Deslízate sobre aguas que brillan en la oscuridad en un paddle nocturno guiado por una bahía protegida." }, img: "/images/biolum.jpg", alt: "Bioluminescent water glowing around a paddleboard at night, Riviera Nayarit" },
  { id: "sup", name: { en: "Sunrise paddleboard", es: "Paddleboard al amanecer" }, dest: "nayarit", destLabel: "Punta Mita", duration: { en: "2 hrs", es: "2 h" }, type: "water", desc: { en: "Calm, golden water and an easy start — perfect for first-timers and early risers.", es: "Agua dorada y tranquila, inicio fácil — ideal para principiantes y madrugadores." }, img: "/images/paddleboard.jpg", alt: "Paddleboarder on calm water at sunrise near Punta Mita" },
  { id: "snorkel", name: { en: "Marietas snorkeling tour", es: "Snorkel en Islas Marietas" }, dest: "nayarit", destLabel: "Islas Marietas", duration: { en: "Half day", es: "Medio día" }, type: "water", desc: { en: "Explore the reefs and sea life around the protected Islas Marietas with a local guide.", es: "Explora arrecifes y vida marina alrededor de las protegidas Islas Marietas con guía local." }, img: "/images/snorkel.jpg", alt: "Snorkelers exploring reef at Islas Marietas" },
  { id: "surf", name: { en: "Beginner surf lesson", es: "Clase de surf para principiantes" }, dest: "nayarit", destLabel: "Sayulita", duration: { en: "1.5 hrs", es: "1.5 h" }, type: "adventure", desc: { en: "Catch your first wave in Sayulita with patient instructors and all gear included.", es: "Toma tu primera ola en Sayulita con instructores pacientes y equipo incluido." }, img: "/images/surf.jpg", alt: "Beginner surf lesson in the waves at Sayulita" },
  { id: "yacht", name: { en: "Private yacht day", es: "Día en yate privado" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "Full day", es: "Día completo" }, type: "private", desc: { en: "Your own boat and crew on Banderas Bay — swim, snorkel and watch the sunset.", es: "Tu propio barco y tripulación en Bahía de Banderas — nada, snorkel y atardecer." }, img: "/images/yacht.jpg", alt: "Private yacht anchored in Banderas Bay" },
  { id: "whale", name: { en: "Whale watching (in season)", es: "Avistamiento de ballenas (temporada)" }, dest: "nayarit", destLabel: "Banderas Bay", duration: { en: "3 hrs", es: "3 h" }, type: "family", desc: { en: "Witness humpback whales in Banderas Bay during the winter migration season.", es: "Observa ballenas jorobadas en Bahía de Banderas durante la migración invernal." }, img: "/images/whale.jpg", alt: "Humpback whale breaching in Banderas Bay during whale season" },
  { id: "chichen", name: { en: "Chichén Itzá day tour", es: "Tour a Chichén Itzá" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Full day", es: "Día completo" }, type: "culture", desc: { en: "A full-day journey to one of the New Seven Wonders, with a knowledgeable guide.", es: "Viaje de día completo a una de las Nuevas Siete Maravillas, con guía experto." }, img: "/images/chichen.jpg", alt: "The El Castillo pyramid at Chichén Itzá" },
  { id: "isla", name: { en: "Isla Mujeres catamaran", es: "Catamarán a Isla Mujeres" }, dest: "maya", destLabel: "Isla Mujeres", duration: { en: "Full day", es: "Día completo" }, type: "family", desc: { en: "Sail turquoise Caribbean water to Isla Mujeres for snorkeling, lunch and beach time.", es: "Navega aguas turquesa del Caribe hacia Isla Mujeres para snorkel, comida y playa." }, img: "/images/catamaran.jpg", alt: "Catamaran sailing toward Isla Mujeres on turquoise water" },
  { id: "hiking", name: { en: "Jungle hike to hidden waterfalls", es: "Caminata a cascadas escondidas" }, dest: "nayarit", destLabel: "Riviera Nayarit", duration: { en: "Half day", es: "Medio día" }, type: "adventure", desc: { en: "Trek through tropical forest to discover secret cascades and natural swimming holes with a local guide.", es: "Caminata por bosque tropical hasta cascadas secretas y pozas naturales con guía local." }, img: "/images/jungle.jpg", alt: "Hikers walking through tropical jungle toward a hidden waterfall" },
  { id: "fishing", name: { en: "Deep-sea fishing", es: "Pesca de altura" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "5 hrs", es: "5 h" }, type: "private", desc: { en: "Head offshore with experienced captains targeting mahi-mahi, marlin and tuna in the Pacific.", es: "Salida mar adentro con capitanes experimentados buscando dorado, marlin y atún en el Pacífico." }, img: "/images/fishing.jpg", alt: "Angler holding a large mahi-mahi on a fishing boat" },
  { id: "catamaran-pv", name: { en: "Catamaran sunset cruise", es: "Catamarán al atardecer" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "3 hrs", es: "3 h" }, type: "water", desc: { en: "Relax aboard a spacious catamaran with music, drinks and golden-hour views over Banderas Bay.", es: "Relájate a bordo de un catamarán con música, bebidas y vistas doradas sobre Bahía de Banderas." }, img: "/images/catamaran-pv.jpg", alt: "Catamaran sailing at sunset on Banderas Bay" },
  { id: "sailing", name: { en: "Private sailing experience", es: "Velero privado" }, dest: "nayarit", destLabel: "Punta Mita", duration: { en: "Full day", es: "Día completo" }, type: "private", desc: { en: "A full day on a sleek sailboat with skipper — snorkel, swim and beach-hop at your own pace.", es: "Un día completo en velero con patrón — snorkel, nado y playas a tu ritmo." }, img: "/images/sailing.jpg", alt: "Sailboat gliding on calm Pacific waters near Punta Mita" },
  { id: "boat-tour", name: { en: "Banderas Bay boat tour", es: "Tour en lancha por la bahía" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "3 hrs", es: "3 h" }, type: "family", desc: { en: "A scenic coastal cruise with stops for swimming, wildlife spotting and great photo angles.", es: "Paseo costero con paradas para nadar, avistar fauna y ángulos perfectos para fotos." }, img: "/images/boat-tour.jpg", alt: "Tour boat cruising along the coastline of Banderas Bay" },
  { id: "atv", name: { en: "ATV jungle adventure", es: "Cuatrimoto en la selva" }, dest: "nayarit", destLabel: "Sayulita", duration: { en: "3 hrs", es: "3 h" }, type: "adventure", desc: { en: "Ride off-road trails through tropical forest, riverbeds and mountain viewpoints near Sayulita.", es: "Recorre senderos off-road por bosque tropical, cauces de río y miradores montaña cerca de Sayulita." }, img: "/images/atv.jpg", alt: "ATV riding through tropical jungle trails" },
  { id: "rzr", name: { en: "RZR off-road tour", es: "RZR off-road" }, dest: "nayarit", destLabel: "Sayulita", duration: { en: "3 hrs", es: "3 h" }, type: "adventure", desc: { en: "Take the wheel of a powerful RZR buggy and explore dusty trails, hills and hidden backroads.", es: "Conduce un buggy RZR y explora caminos polvorientos, colinas y rutas escondidas." }, img: "/images/rzr.jpg", alt: "RZR dune buggy on dusty mountain trail" },
  { id: "zipline", name: { en: "Canopy zipline tour", es: "Tirolesa en la selva" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "3 hrs", es: "3 h" }, type: "adventure", desc: { en: "Fly through the treetops on multiple zipline cables with panoramic jungle and ocean views.", es: "Vuela entre copas de árboles en múltiples cables con vistas panorámicas de selva y océano." }, img: "/images/zipline.jpg", alt: "Zipline canopy tour through tropical forest" },
  { id: "kayak", name: { en: "Sea kayak exploration", es: "Kayak de mar" }, dest: "nayarit", destLabel: "Islas Marietas", duration: { en: "2 hrs", es: "2 h" }, type: "water", desc: { en: "Paddle along the coastline and into sea caves, spotting birds and marine life along the way.", es: "Rema por la costa y cuevas marinas observando aves y vida marina a tu paso." }, img: "/images/kayak.jpg", alt: "Kayakers paddling through clear turquoise water" },
  { id: "tequila", name: { en: "Tequila tasting tour", es: "Tour de tequila" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "3 hrs", es: "3 h" }, type: "culture", desc: { en: "Visit a local distillery to learn about agave cultivation and taste award-winning tequilas.", es: "Visita una destilería local para aprender del agave y degustar tequilas premiados." }, img: "/images/tequila.jpg", alt: "Tequila tasting with agave plants in the background" },
  { id: "food-tour", name: { en: "Local food & taco tour", es: "Tour gastronómico de tacos" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "3 hrs", es: "3 h" }, type: "culture", desc: { en: "Walk through markets and street stalls tasting authentic tacos, ceviche and regional specialties.", es: "Recorre mercados y puestos callejeros probando tacos, ceviche y especialidades regionales." }, img: "/images/food-tour.jpg", alt: "Colorful Mexican street tacos and fresh local dishes" },
  { id: "sunset-cruise", name: { en: "Romantic sunset cruise", es: "Crucero romántico al atardecer" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "Evening", es: "Noche" }, type: "private", desc: { en: "An intimate evening on the water with champagne, dinner and unforgettable Pacific sunset colors.", es: "Velada íntima en el mar con champagne, cena y colores inolvidables del atardecer pacífico." }, img: "/images/sunset-cruise.jpg", alt: "Sunset over the ocean from a boat deck" },
  { id: "scuba", name: { en: "Scuba diving", es: "Buceo" }, dest: "nayarit", destLabel: "Islas Marietas", duration: { en: "Half day", es: "Medio día" }, type: "water", desc: { en: "Explore underwater caves, rock formations and vibrant reef ecosystems with a certified dive guide.", es: "Explora cuevas submarinas, formaciones rocosas y arrecifes vibrantes con guía de buceo certificado." }, img: "/images/scuba.jpg", alt: "Scuba diver exploring underwater rock formations" },
  { id: "horseback", name: { en: "Horseback beach ride", es: "Cabalgata playera" }, dest: "nayarit", destLabel: "Sayulita", duration: { en: "2 hrs", es: "2 h" }, type: "adventure", desc: { en: "Gallop or stroll along sandy shores and jungle trails on well-trained horses at sunset.", es: "Galopa o pasea por playas de arena y senderos de selva a caballo bien entrenado al atardecer." }, img: "/images/horseback.jpg", alt: "Horseback riding along a sandy beach at sunset" },
  { id: "tulum", name: { en: "Tulum ruins & beach", es: "Ruinas de Tulum y playa" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Full day", es: "Día completo" }, type: "culture", desc: { en: "Explore the cliff-top Mayan ruins of Tulum and swim in the Caribbean cove right below.", es: "Explora las ruinas mayas sobre el acantilado y nada en la cala caribeña justo abajo." }, img: "/images/tulum.jpg", alt: "Tulum Mayan ruins overlooking turquoise Caribbean water" },
  { id: "cozumel", name: { en: "Cozumel snorkeling day", es: "Snorkel en Cozumel" }, dest: "maya", destLabel: "Cozumel", duration: { en: "Full day", es: "Día completo" }, type: "water", desc: { en: "A boat trip to Cozumel's famous Palancar reef for world-class snorkeling and beach relaxation.", es: "Viaje en lancha al famoso arrecife Palancar de Cozumel para snorkel de clase mundial y playa." }, img: "/images/cozumel.jpg", alt: "Snorkeler above colorful coral reef in Cozumel" },
  { id: "xcaret", name: { en: "Xcaret eco park", es: "Parque Xcaret" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Full day", es: "Día completo" }, type: "family", desc: { en: "A full day of underground rivers, wildlife, shows and cultural exhibits in a spectacular natural park.", es: "Día completo de ríos subterráneos, fauna, espectáculos y exhibiciones culturales en un parque natural." }, img: "/images/xcaret.jpg", alt: "Underground river swim at Xcaret eco park" },
  { id: "xplor", name: { en: "Xplor adventure park", es: "Parque Xplor" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Full day", es: "Día completo" }, type: "adventure", desc: { en: "Underground ziplines, amphibious vehicles and stalactite river swimming in a jungle setting.", es: "Tirolesas subterráneas, vehículos anfibios y río entre estalactitas en un parque de aventura." }, img: "/images/xplor.jpg", alt: "Underground zipline and stalactites at Xplor adventure park" },
  { id: "xelha", name: { en: "Xel-Há natural park", es: "Parque Xel-Há" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Full day", es: "Día completo" }, type: "family", desc: { en: "Float down lazy rivers, snorkel inlets and enjoy an all-inclusive day in a stunning lagoon park.", es: "Flota por ríos perezosos, hace snorkel en caletas y disfruta un día todo incluido en laguna." }, img: "/images/xelha.jpg", alt: "Lazy river floating through mangroves at Xel-Há natural park" },
  { id: "xenotes", name: { en: "Xenotes cenote circuit", es: "Circuito Xenotes" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Full day", es: "Día completo" }, type: "adventure", desc: { en: "Rappel, zipline and swim through four different cenotes in a single adrenaline-filled day.", es: "Rápel, tirolesa y nado en cuatro cenotes distintos en un día lleno de adrenalina." }, img: "/images/xenotes.jpg", alt: "Zip-lining between cenotes in the Yucatán jungle" },
  { id: "cenote", name: { en: "Cenote swim & snorkel", es: "Cenote para nadar y snorkel" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Half day", es: "Medio día" }, type: "water", desc: { en: "Crystal-clear freshwater cenotes perfect for swimming, snorkeling and photographing limestone formations.", es: "Cenotes de agua dulce cristalina perfectos para nadar, hacer snorkel y fotografiar formaciones." }, img: "/images/cenote.jpg", alt: "Crystal-clear cenote with limestone walls and turquoise water" },
  { id: "mayan-cooking", name: { en: "Mayan village & cooking", es: "Pueblo maya y cocina" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Half day", es: "Medio día" }, type: "culture", desc: { en: "Visit a traditional community, learn about Mayan heritage and cook authentic dishes together.", es: "Visita una comunidad tradicional, aprende sobre herencia maya y cocina platillos auténticos." }, img: "/images/mayan-cooking.jpg", alt: "Traditional Mayan cooking class with fresh local ingredients" },
  { id: "cozumel-dive", name: { en: "Cozumel scuba diving", es: "Buceo en Cozumel" }, dest: "maya", destLabel: "Cozumel", duration: { en: "5 hrs", es: "5 h" }, type: "water", desc: { en: "Two-tank dive on Cozumel's renowned wall reefs with visibility up to 30 meters.", es: "Inmersión de dos tanques en los famosos arrecifes de pared de Cozumel con visibilidad de hasta 30 metros." }, img: "/images/cozumel-dive.jpg", alt: "Scuba diver surrounded by tropical fish on Cozumel reef" },
  { id: "atv-maya", name: { en: "ATV + cenote combo", es: "Cuatrimoto + cenote" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Half day", es: "Medio día" }, type: "adventure", desc: { en: "Ride ATVs through jungle trails and cool off with a swim in a sacred open cenote.", es: "Recorre senderos en cuatrimoto y refréscate nadando en un cenote abierto sagrado." }, img: "/images/atv-maya.jpg", alt: "ATV riding through jungle trail to an open cenote" },
  { id: "sailing-maya", name: { en: "Private sailing Riviera Maya", es: "Velero privado Riviera Maya" }, dest: "maya", destLabel: "Riviera Maya", duration: { en: "Full day", es: "Día completo" }, type: "private", desc: { en: "Your own catamaran or sailboat for the day — snorkel, beach-hop and enjoy Caribbean breeze.", es: "Tu propio catamarán o velero por el día — snorkel, playas y brisa caribeña." }, img: "/images/sailing-maya.jpg", alt: "Catamaran sailing on turquoise Caribbean water" },
  { id: "holbox", name: { en: "Holbox island day trip", es: "Excursión a Holbox" }, dest: "maya", destLabel: "Holbox", duration: { en: "Full day", es: "Día completo" }, type: "family", desc: { en: "A laid-back escape to Holbox: flamingos, shallow turquoise water and pristine beaches.", es: "Escapada relajada a Holbox: flamencos, agua turquesa poco profunda y playas prístinas." }, img: "/images/holbox.jpg", alt: "Flamingos and shallow turquoise water at Holbox island" },
  { id: "sian-kaan", name: { en: "Sian Ka'an biosphere", es: "Reserva Sian Ka'an" }, dest: "maya", destLabel: "Sian Ka'an", duration: { en: "Full day", es: "Día completo" }, type: "adventure", desc: { en: "Boat through mangrove channels, spot wildlife and float in natural canals in a UNESCO reserve.", es: "Navega por canales de manglar, observa fauna y flota en canales naturales de una reserva UNESCO." }, img: "/images/sian-kaan.jpg", alt: "Mangrove channel and wildlife in Sian Ka'an biosphere" },
  { id: "coco-bongo", name: { en: "Coco Bongo night show", es: "Show de Coco Bongo" }, dest: "maya", destLabel: "Cancún", duration: { en: "Evening", es: "Noche" }, type: "family", desc: { en: "An explosive evening of live performances, music and acrobatics at Cancún's iconic club.", es: "Velada explosiva de actuaciones en vivo, música y acrobacias en el icónico club de Cancún." }, img: "/images/coco-bongo.jpg", alt: "Vibrant Coco Bongo show stage with performers" },
  { id: "isla-contoy", name: { en: "Isla Contoy nature reserve", es: "Reserva Isla Contoy" }, dest: "maya", destLabel: "Isla Contoy", duration: { en: "Full day", es: "Día completo" }, type: "family", desc: { en: "A protected island paradise for birdwatching, snorkeling and escaping the crowds.", es: "Paraíso de isla protegida para avistamiento de aves, snorkel y escapar de las multitudes." }, img: "/images/isla-contoy.jpg", alt: "Pristine white sand beach at Isla Contoy nature reserve" },
  { id: "spa-day", name: { en: "Beachfront spa day", es: "Día de spa frente al mar" }, dest: "nayarit", destLabel: "Puerto Vallarta", duration: { en: "3 hrs", es: "3 h" }, type: "private", desc: { en: "Massage, facial and hydrotherapy in an open-air cabana with ocean breeze and Pacific views.", es: "Masaje, facial e hidroterapia en cabaña al aire libre con brisa del océano y vistas del Pacífico." }, img: "/images/spa-day.jpg", alt: "Beachfront massage cabana overlooking the Pacific ocean" },
];

export const getExperience = (id: string) => ALL_EXPERIENCES.find((x) => x.id === id);

export const typeLabels: Record<string, { en: string; es: string }> = {
  water: { en: "Water", es: "Mar" },
  adventure: { en: "Adventure", es: "Aventura" },
  culture: { en: "Culture", es: "Cultura" },
  private: { en: "Private", es: "Privado" },
  family: { en: "Family", es: "Familia" },
};
